import { API_BASE_URL } from '../config';
import { MaintenanceLog } from '../types'; // Assuming types are updated

// Type for the data sent to create a new log, omitting fields generated by backend
export type NewMaintenanceLogData = Omit<MaintenanceLog, 'id' | 'created_at' | 'updated_at'>;

/**
 * Fetches maintenance logs from the backend.
 * @param filters Optional filters for machine_name, start_date, end_date.
 */
export const fetchMaintenanceLogs = async (filters?: {
  machine_name?: string;
  start_date?: string; // YYYY-MM-DD
  end_date?: string;   // YYYY-MM-DD
}): Promise<MaintenanceLog[]> => {
  const queryParams = new URLSearchParams();
  if (filters?.machine_name) {
    queryParams.append('machine_name', filters.machine_name);
  }
  if (filters?.start_date) {
    queryParams.append('start_date', filters.start_date);
  }
  if (filters?.end_date) {
    queryParams.append('end_date', filters.end_date);
  }

  const response = await fetch(`${API_BASE_URL}/machines/maintenance-logs?${queryParams.toString()}`);

  if (!response.ok) {
    const errorData = await response.json().catch(() => ({ message: 'Failed to fetch maintenance logs and parse error' }));
    throw new Error(errorData.message || 'Failed to fetch maintenance logs');
  }

  const logs: MaintenanceLog[] = await response.json();
  return logs;
};

/**
 * Adds a new maintenance log to the backend.
 * @param logData The data for the new maintenance log.
 */
export const addMaintenanceLog = async (logData: NewMaintenanceLogData): Promise<MaintenanceLog> => {
  const response = await fetch(`${API_BASE_URL}/machines/maintenance-logs`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(logData),
  });

  if (!response.ok) {
    const errorData = await response.json().catch(() => ({ message: 'Failed to add maintenance log and parse error' }));
    throw new Error(errorData.message || 'Failed to add maintenance log');
  }

  const newLog: MaintenanceLog = await response.json();
  return newLog;
};
